# Generated by Django 2.2.3 on 2019-07-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('lokasi', models.CharField(max_length=40)),
                ('tentang', models.TextField(max_length=300)),
                ('website', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('posisi', models.CharField(max_length=40)),
                ('header_logo', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=30)),
                ('kualifikasi', models.TextField(max_length=3000)),
                ('level_karir', models.CharField(max_length=20)),
                ('tahun_pengalaman', models.CharField(max_length=20)),
                ('kualifikasi_pendidikan', models.CharField(max_length=20)),
                ('tipe_pekerjaan', models.CharField(max_length=20)),
                ('lainnya', models.CharField(max_length=40)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEBLOKER.Perusahaan')),
            ],
        ),
    ]
